cookie:
  expiry_days: 30
  key: supersecretkey123
  name: xtrafi_auth
credentials:
  preauthorized: {}
  usernames:
    admin:
      first_name: Administrateur
      last_name: Xtrafi
      password: $2b$12$K00VvM58.C/xV/fJJmQejejfayLkdDPtSnQE076a4mF/mq8UXaVY6
      roles:
      - admin
    idacoul:
      name: Ida COULIDATY
      organizations:
      - orga 1
      - orga  2
      password: $2b$12$DcpnrPj1hPUb9Wxp.PCbeub8MdGs/qQmsoG8kuQPWAhWK3StsFbJa
      roles:
      - user
      - admin
    idacoul22:
      name: Ida COULIDATYyyyyyy
      organizations:
      - orga 1
      - orga  2
      password: $2b$12$awq9CbY0m0A3yn47y9rJ/ukLOUl5r2PkkImmFNut2YzObZ20o703y
      roles:
      - viewer
    idacoul271196:
      name: Ida COULIDATYoo
      organizations:
      - orga 1
      - orga  2
      password: $2b$12$IrAGSxURvzjMLm.PYENCwe1FliY7aHSJeYdbSOKTQjjDOUN7kyxbC
      roles:
      - admin
    user1:
      name: ''
      organizations: []
      password: $2b$12$ALRhd9.csR1yfMMF.jfqSem3YmzzqHPhX4ma2bjFPI6YPoj1aJUCm
      roles:
      - viewer
