cookie:
  expiry_days: 1
  key: supersecretkey123
  name: xtrafi_auth
credentials:
  preauthorized: {}
  usernames:
    admin:
      first_name: Administrateur
      last_name: Xtrafi
      password: admin
      roles:
      - admin
    idacoul:
      name: Ida COULIDATY
      organizations:
      - orga 1
      - orga 2
      password: idacoul
      roles:
      - user
      - admin
    fperdrix:
      name: Franck PERDRIX
      organizations:
      - orga 1
      - orga 2
      password: fperdrix
      roles:
      - viewer
      - admin
      - user
    fp_rpdt01:
      name: Franck PERDRIX
      organizations:
      - orga 1
      password: fp_rpdt01
      roles:
      - user
    rpdt_02:
      name: Répondant 02
      organizations:
      - orga3
      password: rpdt_02
      roles:
      - user
